# Generated by Django 4.1.7 on 2023-04-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_applicant_id_alter_jobdescription_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
